sudo: required
services:
  -docker

before_install:
  - docker build -t mir23cr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run mir23cr/react-test npm run test -- --coverage

after_success:
  - docker build -t mir23cr/multi-client ./client
  - docker build -t mir23cr/multi-nginx  ./ngnix 
  - docker build -t mir23cr/multi-server ./server
  - docker build -t mir23cr/multi-worker ./worker
  # Login in Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_ID --password-stdin
  # Take those images and push them to docker hub.
  - docker push mir23cr/multi-client
  - docker push mir23cr/multi-nginx
  - docker push mir23cr/multi-server
  - docker push mir23cr/multi-worker
